export const SET_USER = 'SET_USER'
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_LIST = 'SET_LIST'
export const SET_FILTER = 'SET_FILTER'
export const SET_FAVORITES = 'SET_FAVORITES'
export const SET_SORT = 'SET_SORT'
